apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-backend
  namespace: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: akrana2006/backend-image:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: db-service
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root123"
            - name: DB_NAME
              value: "taskmanager"
          ports:
            - containerPort: 5000
